name: bitcoindart
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 3.0.2
homepage: https://github.com/keybagio/bitcoindart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bech32:
    git:
      url: https://github.com/cypherstack/bech32.git
      ref: 6a3388ff8f62c1fa5e624bb7f36c8e71fe53428d
  bip32:
    git:
      url: https://github.com/cypherstack/bip32-dart
      ref: 9a7e9b9bad9872c69dd1383d6b2e6090f85148fc
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 20bc8ca0bf0a30c6965977a26c41475a9e862020
  pointycastle: ^4.0.0
  hex: ^0.2.0
  bs58check: ^1.0.1
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.0
